### ISSUE TITLE
Getting started: HTML links do not work

### ISSUE THREAD

**Issue by lucasmilin** [akeneo/pim-api-docs#197]
Hi,

All HTML links at the end of Getting started section do not work. Could you fix it please?

Thanks!

**Comment by NolwennP** [comment]
Hi @lucasmilin!

I just check them, and they seem to work fine.
Maybe I didn't test the right links. Can you tell me what are they precisely?

Thanks!

**Comment by NolwennP** [comment]
Oh right!
I thought you were talking about the getting started of the HTTP API, not the PHP client.
On my way to fix those links.

Thanks for telling us about it!
