### ISSUE TITLE
Currency fields types

### ISSUE THREAD

**Issue by JoxMartin** [akeneo/pim-api-docs#277]
Hi,

I noticed a typo in the api doc.

I was trying to add a currency field via the PHP API client to my catalog and use for this the `pim_catalog_price` type as mentionned in the doc but the real currency type is `pim_catalog_price_collection`

**Comment by NolwennP** [comment]
Hi @JoxMartin!
Thanks for raising this issue.
I created a PR to fix this: #278

**Comment by NolwennP** [comment]
Fixed, and merged. It will be deployed soon.

Thanks again for your help! 🙂
