### ISSUE TITLE
Create Product Media File does not work

### ISSUE THREAD

**Issue by martin25828** [akeneo/pim-api-docs#294]
Hello,

we have a Java application that generates for us some product data. And also some product images. 

We tried to use the web API to send the created product images to Akeneo. But currently, it seems it's not possible to create the picture through a Java REST client. The other connections points of the API (product, attributes, families) we are using without any problems. 
We tried it with the generated Java code from Postman for Unirest and also OK HTTP without success. When we are using Postman and also curl it works fine. But with Java it seems not. It seems that the file was created through the web api but there is no picture is shown.
The Code we use for this is the following:
HttpResponse<String> responseImage = Unirest.post("http://pim.akeneo.com/api/rest/v1/media-files")
				  .header("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW")
				  .header("Authorization", "Bearer " + this.tokenAkeneo)
				  .header("Content-Type", "multipart/form-data")
				  .header("Cache-Control", "no-cache")
				  .header("Host", "pim.akeneo.com")
				   .header("Connection", "keep-alive")
				  .header("cache-control", "no-cache")
				  .body("------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"product\"\r\n\r\n{\"identifier\":\"test\", \"attribute\":\"image\", \"scope\": null,\"locale\":null}\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"file\" filename=@C:\\Users\\Xuser\\Desktop\\BilderBeispile\\imageSource\\11SE500ExP3000x.jpg \r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW")
				  .asString();

According to the documentation we have to add also the binary of the picture which we tried also without success. Any idea what we are doing wrong?

Thank you and Regards,

Martin

**Comment by NolwennP** [comment]
Hi @martin25828,
I suggest you go and ask your question directly on the PIM repository: https://github.com/akeneo/pim-community-dev/issues as it seems to be a PIM issue and not a documentation issue.
Indeed, this repository only holds the source code of the documentation of the API, not its implementation in itself. You'll have more chances to get an answer there.

Regards,
Nolwenn
