### ISSUE TITLE
Local build creates broken akeneo-web-api.json

### ISSUE THREAD

**Issue by cplaetzinger** [akeneo/pim-api-docs#304]
I cloned the repository for some local testing. Calling `yarn serve` modifies and breakes the file content/swagger/akeneo-web-api.json. I attached a zipped version of the broken file. Any idea what is going wrong here?
[akeneo-web-api.json.gz](https://github.com/akeneo/pim-api-docs/files/3887149/akeneo-web-api.json.gz)

**Comment by LevFlavien** [comment]
Not reproduced in current version. Closing this since this is old.
