### ISSUE TITLE
Link not well generated

### ISSUE THREAD

**Issue by Doodoune** [akeneo/pim-api-docs#350]
https://api.akeneo.com/guides/dam-connection/synchronize-assets.html#dealing-with-options

**Actually:**
`<a href="api-reference.html#patch_asset_attributes__attribute_code__options__code_">patch attribute options</a>`

Generate this URL (ERROR 404):
https://api.akeneo.com/guides/dam-connection/api-reference.html#patch_asset_attributes__attribute_code__options__code_ 

**Expected behaviour:**

Generate this code:
`<a href="/api-reference.html#patch_asset_attributes__attribute_code__options__code_">patch attribute options</a>`

Generate this URL:
https://api.akeneo.com/api-reference.html#patch_asset_attributes__attribute_code__options__code_

**Comment by NolwennP** [comment]
Fixed by #356
