### ISSUE TITLE
Link to a page without correct CSS

### ISSUE THREAD

**Issue by Doodoune** [akeneo/pim-api-docs#351]
https://api.akeneo.com/documentation/troubleshooting.html#base-64-not-correctly-encoded

Click on the link to go to "Postman collection", it refers to this page https://api.akeneo.com/getting-started-postman-collection.html that is not well designed:
![Screenshot from 2020-02-27 11-16-37](https://user-images.githubusercontent.com/34027529/75435081-cecdb700-5952-11ea-918a-1ea2c3edc21d.png)

**Comment by Doodoune** [comment]
An another page like that:
https://api.akeneo.com/getting-started-admin.html

![Screenshot from 2020-02-27 11-24-09](https://user-images.githubusercontent.com/34027529/75435683-b14d1d00-5953-11ea-93f0-e123e3b00cbc.png)

**Comment by Doodoune** [comment]
And another one:
https://api.akeneo.com/getting-started.html

![Screenshot from 2020-02-27 11-24-56](https://user-images.githubusercontent.com/34027529/75435755-cb86fb00-5953-11ea-95cd-8d622982dd94.png)

**Comment by NolwennP** [comment]
Those pages are not supposed to be still in production. I fixed the 2 first dead links here: #356 
How did you access the last one? I couldn't find any dead link to it.

**Comment by Doodoune** [comment]
The last one is not foundable in my tools to find deadlink so it has been resolved.
But I found a new one :( 

https://api.akeneo.com/api-reference-asset-manager.html
![Screenshot from 2020-03-03 10-42-47](https://user-images.githubusercontent.com/34027529/75762912-c18e3f00-5d3b-11ea-9e36-07a73221e1e9.png)

But I don't know where it's called.

Tool used:
https://www.deadlinkchecker.com/website-dead-link-checker.asp
