### ISSUE TITLE
Missing example for creating media-file

### ISSUE THREAD

**Issue by pardahlman** [akeneo/pim-api-docs#51]
In general the API documentation is excellent! I especially appreciate the examples of payload 👌 !

I'm currently trying to use the endpoint for [creating a new media file](https://api.akeneo.com/api-reference.html#post_media-files). Initially, I stumbled on an issues (described here https://github.com/akeneo/pim-community-dev/issues/6118) that made my requests return `415 Unsupported Media Type`. It turned out it was due to a known bug that will be patched in an upcoming version of Akeneo PIM.

With the work-around in place, I get a `422 Unprocessable Entity` with the body

```json
{
  "code": 422,
  "message": "Property \"product\" is required."
}
```

According to the documentation, `product` should be "a JSON string that follows this formula `'{"identifier":"product_identifier", "attribute":"attribute_code", "scope":"channel_code","locale":"locale_code"}'`"

Which I believe is what I'm doing, here's the curl from postman

```
curl -X POST \
  http://localhost:8080/api/rest/v1/media-files \
  -H 'authorization: Bearer MTA0YWQ3YjM2ZmJkOWIyZWM1M2E2MTA0Y2ZlOWQ0NTJiYzcxNmI4NTVjMWM4YmEzMWNiZGM1NmJkY2Y2MWVlZg' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -H 'postman-token: 0c672859-3987-353c-3306-f2468fa478d6' \
  -F 'product={"identifier":"product-identifier","attribute":"Product_Image_Medium","scope":"ecommerce","locale":"sv_SE"}' \
  -F file=@filename.png
```

I've also tried to send the product payload with espaced `\"`, with wrapping `'` and various different formats but no success.

I'm also a bit uncertain on how the `file` property values should look like. My first guess is like a string with only zeroes and ones, but it would be nice to have that confirmed.

I think it could be helpful if the documentation regarding this endpoint was updated with some sort of example, or perhaps a bit more elaborated description on how the API expects the data.

**Comment by ahocquard** [comment]
Unfortunately, Postman generation is broken. Here is a working example (not that you should not precise the boundary yourself): 

```
curl -v -X POST -H "Authorization: Bearer you_token" -H "Content-Type: multipart/form-data" -F 'product={"identifier":"10699783","attribute":"picture","scope": null,"locale":null}' -F "file=@you_file_path" "http://pcd.dev/api/rest/v1/media-files"
```

Also, because the search is JSON, wrapped it with `'`.

Note : no need to add `Accept` header with `*/*` in postman and curl because they are doing it automatically.

It is, in my opinion, properly documented. But `multipart/form-data` is not the most common format and can be complicated the first time. 
But it's the role of the client to abstract this complexity ;)

This format is probably already implemented by your HTTP client in .NET (I don't know .NET world !).

**Comment by pardahlman** [comment]
Hi @ahocquard - thanks for getting back to me 👍 

You are absolutely right, there is a `MultipartFormDataContent` in .NET that is meant to be used just in cases like this. In fact, that was my first approach, but it return the same 422 ("_Property \"product\" is required_") as when I later tried to get it to work in Postman. Here's the request produced from the .NET client

```
POST http://127.0.0.1:8080/api/rest/v1/media-files HTTP/1.1
Connection: Keep-Alive
Content-Type: multipart/form-data; boundary="fb574b49-7809-4ca7-854a-025e9c1298db"
Accept: */*, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer YTNlM2I0ZjQ4MjkyM2I4Y2FjYzU1MzBjMjc5ZGQxYjhmZWRlYmRlNWVmMTdiMjI2MzcyZWJhYmJhZTVhNjA1ZQ
Cookie: BAPID=f97d5d9aa6f72ebb71d2da3e6e5fd4e2
Content-Length: 5919
Host: 127.0.0.1:8080

--fb574b49-7809-4ca7-854a-025e9c1298db
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=product

"{\"identifier\":\"product-identifier\",\"attribute\":\"Product_Image_Medium\",\"scope\":\"ecommerce\",\"locale\":\"sv_SE\"}"
--fb574b49-7809-4ca7-854a-025e9c1298db
Content-Disposition: form-data; name=file

 PNG

```
Looks good?

I also tried the cURL you gave me, only chaining the token, URL, but still get the 442

![image](https://cloud.githubusercontent.com/assets/1032755/25545348/b729205e-2c5e-11e7-9b76-99de6399921b.png)

Any other ideas?

**Comment by ahocquard** [comment]
Could you post the result of the file `/tmp/stdout` after the curl request :
 
```
curl -v -X POST 
-H "Authorization: Bearer $token" 
-H "Content-Type: multipart/form-data" 
-F 'product={"identifier":"10699783","attribute":"picture","scope": null,"locale":null}' 
-F "file=@/Users/ahocquard/Desktop/test?ooo=iii.png" "http://pcd.dev/api/rest/v1/media-files" 
--trace-ascii /tmp/stdout
```

Verbose does not display the content of the body. Maybe it's due to a difference with curl on windows. It's very weird to not have the same behavior as me.

Personally, I have : 

```
== Info:   Trying 127.0.0.1...
== Info: Connected to pcd.dev (127.0.0.1) port 80 (#0)
=> Send header, 338 bytes (0x152)
0000: POST /api/rest/v1/media-files HTTP/1.1
0028: Host: pcd.dev
0037: User-Agent: curl/7.43.0
0050: Accept: */*
005d: Authorization: Bearer MjdiMjkzY2NhYWJmMzAzYTQyZDc5OGQ3NGQwNmRkZG
009d: VjNDE0NzE4NDFiNzI1ZTI0YWYwMWVhNmQ3N2NkY2VlZQ
00cb: Content-Length: 1091363
00e4: Expect: 100-continue
00fa: Content-Type: multipart/form-data; boundary=--------------------
013a: ----ae4c4112179aa0f4
0150:
<= Recv header, 23 bytes (0x17)
0000: HTTP/1.1 100 Continue
=> Send data, 331 bytes (0x14b)
0000: --------------------------ae4c4112179aa0f4
002c: Content-Disposition: form-data; name="product"
005c:
005e: {"identifier":"10699783","attribute":"picture","scope": null,"lo
009e: cale":null}
00ab: --------------------------ae4c4112179aa0f4
00d7: Content-Disposition: form-data; name="file"; filename="test?ooo=
0117: iii.png"
0121: Content-Type: application/octet-stream
0149:
=> Send data, 16384 bytes (0x4000)
0000: .PNG
0006: ......IHDR.......".......t....|iCCPICC Profile..(.c``*I,(.aa``..
0046: +).rwR...R`...... .`. ..\\.......|...../...J..y...|..6..rV%:....
0086: wJjq2..#....R...d...:..E%@.. [.....>.d.....d....!.. v.....V....d
00c6: K...I......a[.....)@..........E...R....I..9.0;@.......r...0x0.0(
0106: 0.3.0X2.28..V...:..T.e.g.(8.C6U.9?...$.HG.3/YOG........g..?..Mg.
0146: ;..._..`.......K....}....)...<..~k..m.......g..B._.fl.a.810.....
0186: .....$..................@..$wi..k......iTXtXML:com.adobe.xmp....
```

**Comment by pardahlman** [comment]
Sure! Here's the result of the curl: [curl.txt](https://github.com/akeneo/pim-api-docs/files/966354/curl.txt).

It does look very similar to your request, but perhaps you can make more sense of it?

**Comment by ahocquard** [comment]
The json of the product seems not complete and invalid (no double quote around the keys) : 

```
{identifier:10699783,attribute:picture,scope:
```

Did you resolve your problem ? (you mentioned that it was finally ok in another issue)
Don't hesitate to post the solution for the community !

**Comment by pardahlman** [comment]
Heya - sorry, not yet. I'll hopefully find time in the end of this week to look into this!

**Comment by pardahlman** [comment]
Hello @ahocquard,

I think I've worked out most of the kinks for the media file upload from the .NET Client 👏 .

I had two different problems, the first one was related to `product` and was due to the fact that the json I provided escaped the strings with quotation mark (`\"`) which the deserializer in the API didn't like.

Next problem was due to the fact that I provided binaries of the file, but missed to provide a _file name_ which is also required. It makes sense when you think about it, but I got thrown of by the documentation ("`file`  (_string / binary_) • The binaries of the file") 🤷‍♂️ .

Anyways, glad for your help, the cURL you provided was the key for me to see what I did wrong

**Comment by ahocquard** [comment]
Nice catch, I didn't know it was mandatory. I think that we can close this issue. I will try to put it in a troubleshooting page for common issues with the different endpoints.

Thanks for the feedback, it allows to improve our documentation !

**Comment by PabloPKP** [comment]
Hi:

I have a similar error updating a image in a product. I am usgin this endpoint "**/api/rest/v1/media-files**" and it is workin fine because the response is 201 (created), but the image is not shown in akeneo. I have tryied in Java and PHP and it not working, but in postman is working perfectly and the image is shown perfectly in Akeneo.. My php code is:

$curl = curl_init();
$data="------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"file\"; filename=\"Foro.jpg\"\r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"product\"\r\n\r\n{\n\t\"identifier\": \"578-CX1003\",\n\t\"attribute\": \"Foto\",\n\t\"scope\": null,\n\t\"locale\": null\n}\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--";
curl_setopt_array($curl, array(
  CURLOPT_URL => "host/api/rest/v1/media-files",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_SSL_VERIFYPEER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => $data,
  CURLOPT_HTTPHEADER => array(
    "Authorization: Bearer Token",
    "content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);
print_r($response);
curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

This code is copied from label "code" from postman.

Thanks.

**Comment by ahocquard** [comment]
Hello,

Why don't you use the PHP client we provide? I think it would avoid to do this kind of tricky thing on your side.

Regards,
Alexandre

**Comment by PabloPKP** [comment]
Thanks @ahocquard :

i would like to do this with curl request because with your PHP client i should install it in akeneo server and execute all the sentences from akeneo server. 
Besides importing the image I also import many attributes from Magento 2 e-commerce.

Regards.

**Comment by ahocquard** [comment]
I don't understand the problem. You can use the PHP client on a remote server, exactly like with native curl. You don't need to install it on an akeneo server (if you mean the server running akeneo PIM).

**Comment by PabloPKP** [comment]
thanks, i thought that i should to install it in akeneo server. Anyway i would like to be able to call by curl to upload images in products if possible.

thanks.

**Comment by ahocquard** [comment]
Please understand that we can't debug what you provided.
It's clearly not a best practice to use curl directly.

If you want to do it, here some hints:
- try to upload with curl and generate the HTTP

I dont' see anything about the upload of the file itself (see some payload in comments above):
```
Content-Disposition: form-data; name="file"; filename="test?ooo=
0117: iii.png"
```

For your information, with the PHP client, it's as simple as that:
https://api.akeneo.com/php-client/resources.html#create-a-new-media-file
