### ISSUE TITLE
[Missing] Document `Location` values in case of creation/update

### ISSUE THREAD

**Issue by mickaelandrieu** [akeneo/pim-api-docs#55]
Regarding @ahocquard comment, we should document the `Location` behavior.

> All URI creating/updating one single resource (not available on endpoint updating multiple resources) returns a Location header with the URL to the resource.

**Comment by NolwennP** [comment]
Note that it is already documented for the single update endpoints.
Only missing for the creation endpoints.

**Comment by ahocquard** [comment]
Done in https://github.com/akeneo/pim-api-docs/pull/61.
