### ISSUE TITLE
Typo error : menu to modify the role is wrong

### ISSUE THREAD

**Issue by Tipiakus** [akeneo/pim-api-docs#572]
In the page https://api.akeneo.com/apps/how-to-test-my-app.html
In the chapter https://api.akeneo.com/apps/how-to-test-my-app.html#step-1-enable-the-developer-mode-and-the-test-app-creation
The menu is nammed "Settings" where it should be "System" : 
![image](https://user-images.githubusercontent.com/31968713/160282733-51cde385-6d78-4fac-9e40-59fc44535034.png)

**Comment by LevFlavien** [comment]
Hi @Tipiakus 
Thank you for notifying us.
