### ISSUE TITLE
Web API restricted user can access the API

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [akeneo/pim-api-docs#75]
Hi,
I have create a user with the role don't have access to web api. But I can create a token for this using this user credentials (username / password).

![screenshot from 2017-07-11 18-00-48](https://user-images.githubusercontent.com/29775799/28068531-9d9d2aa6-6663-11e7-9106-8ef46f76d4fb.png)
 
Please advise.

**Comment by LevFlavien** [comment]
Closing since the PIM version is outdated and this doesn't seem to concern documentation anyway
